baseURL: "https://jedipunkz.rocks"
title: "jedipunkz 🚀 のブログ"
pagination:
  pagerSize: 8
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: false
buildFuture: true

# GA4 Measurement ID
googleAnalytics: "G-2H91XCYVZ8"

minify:
  disableXML: true

# サイトマップの設定
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

languages:
  ja:
    languageCode: ja
    languageName: "Japanese"
    weight: 1
    menu:
      main:
        - name: About Me
          url: about
          weight: 5

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "SRE・インフラ・Kubernetes・DevOpsについて学ぶ技術ブログ"
  keywords: [SRE, Kubernetes, DevOps, Infrastructure, Cloud, OpenStack, AWS, GCP, Terraform, CI/CD]
  author: jedipunkz
  mainSections: [post]
  schema:
    publisherType: Person
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  defaultTheme: auto
  ShowShareButtons: true
  displayFullLangName: true
  DateFormat: "2006-01-02"
  assets:
    favicon: '/favicon.ico'
    favicon16x16: '/favicon-16x16.png'
    favicon32x32: '/favicon-32x32.png'
    apple_touch_icon: '/apple-touch-icon.png'
  images: ["jedipunkz.jpg"]
  cover:
    image: "jedipunkz.jpg"

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "https://jedipunkz.github.io/jedipunkz.jpg"
    imageTitle: jedipunkz
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "jedipunkz 🚀 のブログ"
    Content: >
      SRE になるために学んでいくブログです
  socialIcons:
    - name: twitter
      url: "https://x.com/jedipunkz"
    - name: github
      url: "https://github.com/jedipunkz"

taxonomies:
  category: categories
  tag: tags

privacy:
  vimeo:
    disabled: true
    simple: true

  x:
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    style: tokyonight-night
    lineNos: false
    lineNumbersInTable: false
