name: PR Check - Hugo Build Test

on:
  pull_request:
    branches:
      - source

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.2'
          extended: true

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Build with Hugo
        run: |
          hugo -t PaperMod

      - name: Check build output
        run: |
          if [ ! -d "public" ]; then
            echo "Build failed: public directory not found"
            exit 1
          fi
          echo "Build successful: public directory exists"

      - name: Comment PR - Build Success
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ **Hugo Build Test Passed!**\n\nサイトが正常に生成されました。マージ後に自動デプロイされます。'
            })
